name: Build and Release

on:
  push:
    branches:
      - main # Dispara o workflow em cada push para a branch main

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x # Configura o .NET 8.0

    - name: Restore dependencies
      run: dotnet restore 9H9P9DTools/9H9P9DTools.csproj

    - name: Build project
      run: dotnet build 9H9P9DTools/9H9P9DTools.csproj --configuration Release --no-restore

    - name: Publish project
      run: dotnet publish 9H9P9DTools/9H9P9DTools.csproj --configuration Release --output ./publish --no-restore

    - name: Archive release
      uses: actions/upload-artifact@v3
      with:
        name: 9H9P9DTools-release
        path: ./publish

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./publish/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}