name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET  (use .NET 8 for build)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore 9H9P9DTools/9H9P9DTools.csproj

      - name: Build (Release)
        run: dotnet build 9H9P9DTools/9H9P9DTools.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish 9H9P9DTools/9H9P9DTools.csproj --configuration Release --no-restore --output ./publish

      - name: Upload artifacts (for workflow)
        uses: actions/upload-artifact@v4
        with:
          name: 9H9P9DTools-publish
          path: ./publish

      - name: Create GitHub release and attach published files
        uses: softprops/action-gh-release@v1
        with:
          files: ./publish/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}